### ISSUE TITLE
node-sass bindings problem

### ISSUE THREAD

**Issue by arsdehnel** [zheeeng/Dockerfiles#1]
Hi, trying to run this and having a little problem with it.  I have keystone working if I just run `node keystone` but then running it in Docker fails me.  I have this `docker-compose.yml` file:

```
version: '3'
services:
  mongodb: 
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
  keystone:
    image: zheeeng/keystonejs
    container_name: keystonejs
    volumes:
      - $PWD:/usr/src/app
    ports:
      - 80:3000
    links:
      - mongodb:mongo
```

When I run `docker-compose up` I get this:

```
keystonejs  | Error: Missing binding /usr/src/app/node_modules/node-sass/vendor/linux-x64-48/binding.node
keystonejs  | Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 6.x
keystonejs  |
keystonejs  | Found bindings for the following environments:
keystonejs  |   - OS X 64-bit with Node.js 7.x
keystonejs  |
keystonejs  | This usually happens because your environment has changed since running `npm install`.
keystonejs  | Run `npm rebuild node-sass` to build the binding for your current environment.
keystonejs  |     at module.exports (/usr/src/app/node_modules/node-sass/lib/binding.js:15:13)
keystonejs  |     at Object.<anonymous> (/usr/src/app/node_modules/node-sass/lib/index.js:14:35)
keystonejs  |     at Module._compile (module.js:570:32)
keystonejs  |     at Object.Module._extensions..js (module.js:579:10)
keystonejs  |     at Module.load (module.js:487:32)
keystonejs  |     at tryModuleLoad (module.js:446:12)
keystonejs  |     at Function.Module._load (module.js:438:3)
keystonejs  |     at Module.require (module.js:497:17)
keystonejs  |     at require (internal/module.js:20:19)
keystonejs  |     at Object.<anonymous> (/usr/src/app/node_modules/node-sass-middleware/middleware.js:3:12)
keystonejs  |     at Module._compile (module.js:570:32)
keystonejs  |     at Object.Module._extensions..js (module.js:579:10)
keystonejs  |     at Module.load (module.js:487:32)
keystonejs  |     at tryModuleLoad (module.js:446:12)
keystonejs  |     at Function.Module._load (module.js:438:3)
keystonejs  |     at Module.require (module.js:497:17)
keystonejs exited with code 1
```

Which makes sense since I'm on macOS and they are different in a Docker container.  I see you have a note to exclude the node_modules folder but I'm not exactly sure what you mean by that.  Remove it from the current directory before running it in Docker? If I do that then it gets me a different error which may be better and may be worse:

```
keystonejs  | ------------------------------------------------
keystonejs  | Mongo Error:
keystonejs  |
keystonejs  | Error: failed to connect to [localhost:27017]
keystonejs  |     at .<anonymous> (/usr/src/modules/node_modules/mongodb/lib/mongodb/connection/server.js:556:25)
keystonejs  |     at emitThree (events.js:116:13)
keystonejs  |     at emit (events.js:194:7)
keystonejs  |     at .<anonymous> (/usr/src/modules/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:156:15)
keystonejs  |     at emitTwo (events.js:106:13)
keystonejs  |     at emit (events.js:191:7)
keystonejs  |     at Socket.<anonymous> (/usr/src/modules/node_modules/mongodb/lib/mongodb/connection/connection.js:534:10)
keystonejs  |     at emitOne (events.js:96:13)
keystonejs  |     at Socket.emit (events.js:188:7)
keystonejs  |     at emitErrorNT (net.js:1278:8)
keystonejs  |     at _combinedTickCallback (internal/process/next_tick.js:74:11)
keystonejs  |     at process._tickCallback (internal/process/next_tick.js:98:9)
keystonejs  | /usr/src/modules/node_modules/keystone/lib/core/mount.js:627
keystonejs  | 			throw new Error('KeystoneJS (' + keystone.get('name') + ') failed to start');
keystonejs  | 			^
keystonejs  |
keystonejs  | Error: KeystoneJS (CPD Styleguide) failed to start
keystonejs  |     at NativeConnection.<anonymous> (/usr/src/modules/node_modules/keystone/lib/core/mount.js:627:10)
keystonejs  |     at emitOne (events.js:96:13)
keystonejs  |     at NativeConnection.emit (events.js:188:7)
keystonejs  |     at NativeConnection.Connection.error (/usr/src/modules/node_modules/mongoose/lib/connection.js:389:8)
keystonejs  |     at /usr/src/modules/node_modules/mongoose/lib/connection.js:416:14
keystonejs  |     at /usr/src/modules/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:57:21
keystonejs  |     at /usr/src/modules/node_modules/mongodb/lib/mongodb/db.js:286:18
keystonejs  |     at /usr/src/modules/node_modules/mongodb/lib/mongodb/db.js:365:7
keystonejs  |     at _combinedTickCallback (internal/process/next_tick.js:67:7)
keystonejs  |     at process._tickCallback (internal/process/next_tick.js:98:9)
keystonejs exited with code 1
```

Any help would be great!

**Comment by arsdehnel** [comment]
So with the second configuration (removing my node_modules folder) and then add this to my `.env`:

```
MONGO_URI=mongodb://mongo:27017/
```

It works to fire up the app. But then I hit `localhost:3000` and keystone complains that it can't find pug (my templating engine choice from yeoman):

```
keystonejs  | Error: Cannot find module 'pug'
keystonejs  |     at Function.Module._resolveFilename (module.js:469:15)
keystonejs  |     at Function.Module._load (module.js:417:25)
keystonejs  |     at Module.require (module.js:497:17)
keystonejs  |     at require (internal/module.js:20:19)
keystonejs  |     at new View (/usr/src/modules/node_modules/express/lib/view.js:80:30)
keystonejs  |     at EventEmitter.render (/usr/src/modules/node_modules/express/lib/application.js:570:12)
keystonejs  |     at ServerResponse.render (/usr/src/modules/node_modules/express/lib/response.js:966:7)
keystonejs  |     at View.<anonymous> (/usr/src/modules/node_modules/keystone/lib/view.js:337:13)
keystonejs  |     at /usr/src/modules/node_modules/keystone/lib/view.js:372:3
keystonejs  |     at /usr/src/modules/node_modules/async/lib/async.js:52:16
keystonejs  |     at /usr/src/modules/node_modules/async/lib/async.js:269:32
keystonejs  |     at /usr/src/modules/node_modules/async/lib/async.js:44:16
keystonejs  |     at /usr/src/modules/node_modules/async/lib/async.js:726:13
keystonejs  |     at /usr/src/modules/node_modules/async/lib/async.js:52:16
keystonejs  |     at async.forEachOf.async.eachOf (/usr/src/modules/node_modules/async/lib/async.js:236:30)
keystonejs  |     at _parallel (/usr/src/modules/node_modules/async/lib/async.js:717:9)
keystonejs  |     at Object.async.parallel (/usr/src/modules/node_modules/async/lib/async.js:731:9)
keystonejs  |     at /usr/src/modules/node_modules/keystone/lib/view.js:364:10
keystonejs  |     at /usr/src/modules/node_modules/async/lib/async.js:181:20
keystonejs  |     at Immediate.iterate (/usr/src/modules/node_modules/async/lib/async.js:262:13)
keystonejs  |     at runCallback (timers.js:649:20)
keystonejs  |     at tryOnImmediate (timers.js:622:5)
keystonejs exited with code 1
```

Which then feels like we're back to the first error I had where the lack of node_modules is causing problems.

**Comment by zheeeng** [comment]
Sorry for reply late, I missed this message. This image will run your keystone with dependency packages, it requires cleaning up the node_modules installed by yourself, then node will find the node_modules within docker container ($NODE_PATH guides nodejs where the packages located).

The pug error may be this keystone container image doesn't contain the pug package which the yeoman template required, for this situation maybe you'd update the package.json through dockerfile and rebuild it.
